---

spring:
  profiles: development
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
  mvc:
    async:
      request-timeout: 3600s
  session:
    timeout: 3600s
  transaction:
    default-timeout: 3600s
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8080
  connection-timeout: -1s
  session:
    timeout: 3600s
eureka:
  instance:
    hostname: api-gateway
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eureka-connection-idle-timeout-seconds: 6000
    eureka-server-read-timeout-seconds: 5000
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    lease:
      duration: 5
ribbon:
  ReadTimeout: 18000000
  ConnectTimeout: 18000000
  MaxAutoRetries: 10
  MaxAutoRetriesNextServer: 10
  OkToRetryOnAllOperations: true
  eureka:
    enabled: true
zuul:
  ignoredServices: "*"
  ignoredPatterns:
    - /auth/noauth/token/**
  host:
    connect-timeout-millis: 18000000
    socket-timeout-millis: 18000000
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
    ebook-service:
      path: /ebook/**
      service-id: ebook-service
    image-service:
      path: /image/**
      service-id: image-service
    music-service:
      path: /music/**
      service-id: music-service
    video-service:
      path: /video/**
      service-id: video-service
    hystrix-dashboard:
      path: /hystrix/**
      service-id: hystrix-dashboard
gateway:
  ribbon:
    ReadTimeout: 18000000
    ConnectTimeout: 18000000
    ServerListRefreshInterval: 15000
    eureka:
      enabled: true
hystrix:
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: -1
      queueSizeRejectionThreshold: 5
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 20
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3600000
management:
  metrics:
    web:
      server:
        auto-time-requests: true
    export:
      elastic:
        host: http://localhost:9200
        enabled: true
        step: 1s
        index: metrics
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    auditevents:
      enabled: true
    httptrace:
      enabled: true
    shutdown:
      enabled: true
    restart:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
---
spring:
  profiles: docker
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
  mvc:
    async:
      request-timeout: 3600s
  session:
    timeout: 3600s
  transaction:
    default-timeout: 3600s
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8080
  connection-timeout: -1s
  session:
    timeout: 3600s
eureka:
  instance:
    hostname: api-gateway
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
    nonSecurePort: ${server.port}
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eureka-connection-idle-timeout-seconds: 6000
    eureka-server-read-timeout-seconds: 5000
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    lease:
      duration: 5
ribbon:
  ReadTimeout: 18000000
  ConnectTimeout: 18000000
  MaxAutoRetries: 10
  MaxAutoRetriesNextServer: 10
  OkToRetryOnAllOperations: true
  eureka:
    enabled: true
zuul:
  ignoredServices: "*"
  ignoredPatterns:
    - /auth/noauth/token/**
  host:
    connect-timeout-millis: 18000000
    socket-timeout-millis: 18000000
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
    ebook-service:
      path: /ebook/**
      service-id: ebook-service
    image-service:
      path: /image/**
      service-id: image-service
    music-service:
      path: /music/**
      service-id: music-service
    video-service:
      path: /video/**
      service-id: video-service
    hystrix-dashboard:
      path: /hystrix/**
      service-id: hystrix-dashboard

hystrix:
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: -1
      queueSizeRejectionThreshold: 5
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 20
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3600000
management:
  metrics:
    web:
      server:
        auto-time-requests: true
    export:
      elastic:
        host: http://elasticsearch:9200
        enabled: true
        step: 1s
        index: metrics
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    auditevents:
      enabled: true
    httptrace:
      enabled: true
    shutdown:
      enabled: true
    restart:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
gateway:
  ribbon:
    ReadTimeout: 18000000
    ConnectTimeout: 18000000
    ServerListRefreshInterval: 15000
    eureka:
      enabled: true
---
spring:
  profiles: aws
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
  mvc:
    async:
      request-timeout: 3600s
  session:
    timeout: 3600s
  transaction:
    default-timeout: 3600s
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
server:
  port: 8080
  connection-timeout: -1s
  session:
    timeout: 3600s
eureka:
  instance:
    hostname: api-gateway
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 3
    nonSecurePort: ${server.port}
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eureka-connection-idle-timeout-seconds: 6000
    eureka-server-read-timeout-seconds: 5000
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    lease:
      duration: 5
ribbon:
  ReadTimeout: 18000000
  ConnectTimeout: 18000000
  MaxAutoRetries: 10
  MaxAutoRetriesNextServer: 10
  OkToRetryOnAllOperations: true
  eureka:
    enabled: true
zuul:
  ignoredServices: "*"
  ignoredPatterns:
    - /auth/noauth/token/**
  host:
    connect-timeout-millis: 18000000
    socket-timeout-millis: 18000000
  routes:
    auth-service:
      path: /auth/**
      service-id: auth-service
    ebook-service:
      path: /ebook/**
      service-id: ebook-service
    image-service:
      path: /image/**
      service-id: image-service
    music-service:
      path: /music/**
      service-id: music-service
    video-service:
      path: /video/**
      service-id: video-service
    hystrix-dashboard:
      path: /hystrix/**
      service-id: hystrix-dashboard

hystrix:
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: -1
      queueSizeRejectionThreshold: 5
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 20
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 3600000
management:
  metrics:
    web:
      server:
        auto-time-requests: true
    export:
      elastic:
        host: http://elasticsearch:9200
        enabled: true
        step: 1s
        index: metrics
  endpoint:
    health:
      enabled: true
    metrics:
      enabled: true
    auditevents:
      enabled: true
    httptrace:
      enabled: true
    shutdown:
      enabled: true
    restart:
      enabled: true
    prometheus:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true
gateway:
  ribbon:
    ReadTimeout: 18000000
    ConnectTimeout: 18000000
    ServerListRefreshInterval: 15000
    eureka:
      enabled: true
---
spring:
  profiles: kubernetes
  application:
    name: api-gateway
  cloud:
    discovery:
      enabled: false
    kubernetes:
      enabled: true
      discovery:
        enabled: true
      ribbon:
        enabled: true
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false
gateway:
  ribbon:
    eureka:
      enabled: false
ribbon:
  eureka:
    enabled: false
