---

spring:
  profiles: development
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
server:
  port: 8080
sidecar:
  port: 8000
  health-uri: http://localhost:8000/health
endpoints:
  restart:
    enabled: true
eureka:
  instance:
    hostname: api-gateway
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    auth-service:
      path: /auth/**
      url: http://localhost:9000
    ebook-service:
      path: /ebook/**
      url: http://localhost:9002
    image-service:
      path: /image/**
      url: http://localhost:9004
    music-service:
      path: /music/**
      url: http://localhost:9006
    video-service:
      path: /video/**
      url: http://localhost:9008
    hystrix-dashboard:
      path: /hystrix/**
      url: http://localhost:7979

---

spring:
  profiles: docker
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
server:
  port: 8080
sidecar:
  port: 8000
  health-uri: http://localhost:8000/health
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: api-gateway
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
encrypt:
  failOnError: false
logging:
  file: log.txt
  level: error
zuul:
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
    ebook-service:
      path: /ebook/**
      serviceId: ebook-service
    image-service:
      path: /image/**
      serviceId: image-service
    music-service:
      path: /music/**
      serviceId: music-service
    video-service:
      path: /video/**
      serviceId: video-service
    hystrix-dashboard:
      path: /hystrix/**
      serviceId: hystrix-dashboard