---

spring:
  profiles: development
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
  http:
    multipart:
      max-file-size: 25600MB
      max-request-size: 25600MB
server:
  port: 8080
sidecar:
  port: 8000
  health-uri: http://localhost:8000/health
endpoints:
  restart:
    enabled: true
eureka:
  instance:
    hostname: api-gateway
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 18000000
  ConnectTimeout: 18000000
  eureka:
    enabled: false
zuul:
  host:
    connect-timeout-millis: 18000000
    socket-timeout-millis: 18000000
  routes:
    auth-service:
      path: /auth/**
      url: http://localhost:9000
    ebook-service:
      path: /ebook/**
      url: http://localhost:9002
    image-service:
      path: /image/**
      url: http://localhost:9004
    music-service:
      path: /music/**
      url: http://localhost:9006
    video-service:
      path: /video/**
      url: http://localhost:9008
    hystrix-dashboard:
      path: /hystrix/**
      url: http://localhost:7979

---

spring:
  profiles: docker
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
  http:
    multipart:
      max-file-size: 25600MB
      max-request-size: 25600MB
server:
  port: 8080
sidecar:
  port: 8000
  health-uri: http://localhost:8000/health
eureka:
  instance:
    hostname: api-gateway
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false
ribbon:
  ReadTimeout: 18000000
  ConnectTimeout: 18000000
  eureka:
    enabled: false
zuul:
  host:
    connect-timeout-millis: 18000000
    socket-timeout-millis: 18000000
  routes:
    auth-service:
      path: /auth/**
      serviceId: auth-service
      url: http://auth-service:9000
    ebook-service:
      path: /ebook/**
      serviceId: ebook-service
      url: http://ebook-service:9000
    image-service:
      path: /image/**
      serviceId: image-service
      url: http://ebook-service:9000
    music-service:
      path: /music/**
      serviceId: music-service
      url: http://ebook-service:9000
    video-service:
      path: /video/**
      serviceId: video-service
      url: http://ebook-service:9000
    hystrix-dashboard:
      path: /hystrix/**
      serviceId: hystrix-dashboard
      url: http://hystrix-dashboard:7979