---

spring:
  profiles: development
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
  http:
    multipart:
      max-file-size: 25600MB
      max-request-size: 25600MB
server:
  port: 8080
sidecar:
  port: 8000
  health-uri: http://localhost:8000/health
endpoints:
  restart:
    enabled: true
eureka:
  instance:
    hostname: api-gateway
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    eureka-connection-idle-timeout-seconds: 3000
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  ReadTimeout: 18000000
  ConnectTimeout: 18000000
  eureka:
    enabled: false
zuul:
  host:
    connect-timeout-millis: 18000000
    socket-timeout-millis: 18000000
  routes:
    auth-service:
      path: /auth/**
      url: http://localhost:9000
    ebook-service:
      path: /ebook/**
      url: http://localhost:9002
    image-service:
      path: /image/**
      url: http://localhost:9004
    music-service:
      path: /music/**
      url: http://localhost:9006
    video-service:
      path: /video/**
      url: http://localhost:9008
    hystrix-dashboard:
      path: /hystrix/**
      url: http://localhost:7979
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 6000000
---

spring:
  profiles: docker
  application:
    name: api-gateway
  cloud:
    config:
      discovery:
        enabled: true
  http:
    multipart:
      max-file-size: 25600MB
      max-request-size: 25600MB
server:
  port: 8080
eureka:
  instance:
    hostname: api-gateway
    preferIpAddress: false
    leaseRenewalIntervalInSeconds: 3
  client:
    fetchRegistry: true
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    eureka-connection-idle-timeout-seconds: 6000
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
ribbon:
  ReadTimeout: 18000000
  ConnectTimeout: 18000000
  MaxAutoRetries: 10
  MaxAutoRetriesNextServer: 10
  OkToRetryOnAllOperations: true
  eureka:
    enabled: false
zuul:
  ignoredServices: "*"
  host:
    connect-timeout-millis: 18000000
    socket-timeout-millis: 18000000
  routes:
    auth-service:
      path: /auth/**
      url: http://auth-service:9000
      service-id: auth-service
      stripPrefix: false
    ebook-service:
      path: /ebook/**
      service-id: ebook-service
      stripPrefix: false
    image-service:
      path: /image/**
      service-id: image-service
      stripPrefix: false
    music-service:
      path: /music/**
      service-id: music-service
    video-service:
      path: /video/**
      service-id: video-service
      stripPrefix: false
    hystrix-dashboard:
      path: /hystrix/**
      service-id: hystrix-dashboard
      stripPrefix: false

hystrix:
  threadpool:
    default:
      coreSize: 100
      maxQueueSize: -1
      queueSizeRejectionThreshold: 5
  command:
    default:
      circuitBreaker:
        sleepWindowInMilliseconds: 30000
        requestVolumeThreshold: 20
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 10000
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false