---

spring:
  profiles: cloud
  application:
    name: config-server
  cloud:
    config:
      discovery:
        enabled: true
        serviceId: config-server
      server:
        git:
          uri: https://github.com/Andrzej997/Streamer-Spring-Cloud-Config-Server
server:
  port: 8888
management:
  endpoints:
    enabled-by-default: false
eureka:
  instance:
    hostname: ${PREFIX:}${spring.application.name}.${application.domain:cfapps.io}
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/

---

spring:
  profiles: development
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andrzej997/Streamer-Spring-Cloud-Config-Server
          clone-on-start: true
      discovery:
        enabled: true
        serviceId: config-server
server:
  port: 8888
management:
  endpoints:
    enabled-by-default: false
eureka:
  instance:
    hostname: config-server
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    prefer-ip-address: true
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
service:
  definition:
    metadata:
        uri: http://${spring.application.name}-mateuszsojka.${application.domain:cfapps.io}
encrypt:
  failOnError: false

---
spring:
  profiles: docker
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andrzej997/Streamer-Spring-Cloud-Config-Server
          clone-on-start: true
      discovery:
        enabled: true
        serviceId: config-server
server:
  port: 8888
management:
  endpoints:
    enabled-by-default: false
eureka:
  instance:
    hostname: config-server
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
encrypt:
  failOnError: false
---
spring:
  profiles: aws
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Andrzej997/Streamer-Spring-Cloud-Config-Server
          clone-on-start: true
      discovery:
        enabled: true
        serviceId: config-server
server:
  port: 8888
management:
  endpoints:
    enabled-by-default: false
eureka:
  instance:
    hostname: config-server
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    nonSecurePort: ${server.port}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
encrypt:
  failOnError: false
---
spring:
  profiles: kubernetes
  application:
    name: config-server
  cloud:
    discovery:
      enabled: false
    kubernetes:
      enabled: true
      discovery:
        enabled: true
      ribbon:
        enabled: true
eureka:
  client:
    enabled: false
    registerWithEureka: false
    fetchRegistry: false
ribbon:
  eureka:
    enabled: false
