---

spring:
  profiles: cloud
  application:
    name: ebook-service
  jpa:
    show_sql: true
    database: POSTGRESQL
    hibernate:
      ddl-auto: none
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}config-server.credentials.uri:http://${PREFIX:}${config-server.${application.domain:cfapps.io}}}
eureka:
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/
  instance:
    hostname: ${PREFIX:}${spring.application.name}.${application.domain:cfapps.io}
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
ribbon:
  eureka:
    enabled: true

---

spring:
  profiles: development
  application:
    name: ebook-service
  cloud:
    config:
      discovery:
        enabled: true
  http:
    multipart:
      max-file-size: 25600MB
      max-request-size: 25600MB
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate
    database: POSTGRESQL
  datasource:
    initialize: false
    url: jdbc:postgresql://localhost:5432/ebookdb
    username: sysadm
    password: sysadm
    driver-class-name: org.postgresql.Driver
    tomcat:
      default-auto-commit: false
    dbcp:
      default-auto-commit: false
server:
  port: 9002
  connection-timeout: -1
  session:
    timeout: 36000
eureka:
  instance:
    hostname: ebook-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
ribbon:
  eureka:
    enabled: false
encrypt:
  failOnError: false
logging:
  file: log.txt
  level: error

---

spring:
  profiles: docker
  application:
    name: ebook-service
  http:
    multipart:
      max-file-size: 25600MB
      max-request-size: 25600MB
  cloud:
    config:
      discovery:
        enabled: true
  jpa:
    show_sql: true
    hibernate:
      ddl-auto: none
    database: POSTGRESQL
  datasource:
    initialize: false
    url: jdbc:postgresql://ebookdb:5432/ebookdb
    username: sysadm
    password: sysadm
    driver-class-name: org.postgresql.Driver
    tomcat:
      default-auto-commit: false
    dbcp:
      default-auto-commit: false
server:
  port: 9002
  connection-timeout: -1
  session:
    timeout: 36000
eureka:
  instance:
    hostname: ebook-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
ribbon:
  eureka:
    enabled: false
encrypt:
  failOnError: false
logging:
  file: log.txt
  level: error

---