---
spring:
  profiles: cloud
  cloud:
    config:
      serviceId: config-server
      discovery:
        enabled: true
server:
  port: 8761
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: eureka-service
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-service-mateuszsojka.cfapps.io/eureka/
  server:
    enable-self-preservation: false

---

spring:
  profiles: development
  cloud:
    config:
      serviceId: config-server
      discovery:
        enabled: true
server:
  port: 8761
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: discovery
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  server:
    enable-self-preservation: false

---

spring:
  profiles: docker
  cloud:
    config:
      serviceId: config-server
      discovery:
        enabled: true
server:
  port: 8761
endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
eureka:
  instance:
    hostname: discovery
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
  server:
    enable-self-preservation: false