apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Values.streamerServiceMonitor.name }}
  labels:
    release: {{ .Values.release }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Values.streamerServiceMonitor.matchName }}
  namespaceSelector:
    matchNames:
      - {{ .Values.streamerServiceMonitor.matchNamespace }}
  endpoints:
    - port: {{ .Values.streamerServiceMonitor.port }}
      interval: {{ .Values.streamerServiceMonitor.interval }}
      path: '{{ .Values.streamerServiceMonitor.path }}'
      honorLabels: true
