apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.apiGateway.name }}
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.apiGateway.name }}
  minReplicas: {{ .Values.apiGateway.minReplicas }}
  maxReplicas: {{ .Values.apiGateway.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.hpaTargetCPUUtilizationPercentage }}
