apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.elasticsearch.name }}
  labels:
    enviroment: {{ .Values.enviroment }}
    app.kubernetes.io/name: {{ .Values.elasticsearch.name }}
    app.kubernetes.io/version: {{ .Values.elasticsearchVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ .Values.enviroment }}
    app.kubernetes.io/managed-by: helm
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.elasticsearch.name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.elasticsearch.port }}
