apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-volume-claim
  labels:
    enviroment: {{ .Values.enviroment }}
    app.kubernetes.io/name: {{ .Values.grafana.name }}
    app.kubernetes.io/version: {{ .Values.grafanaVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ .Values.enviroment }}
    app.kubernetes.io/managed-by: helm
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.grafana.requestStorage }}
