scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 1s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'image-service'
    scrape_interval: 1s
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['image-service:9004']
  - job_name: 'grafana'
    scrape_interval: 1s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['grafana:3000']