version: "3"

networks:
  front:
  back:

services:
  usersdb:
    container_name: usersdb
    image: mateuszsojka/usersdb:latest
    networks:
     - back

  imagedb:
    container_name: imagedb
    image: mateuszsojka/imagedb:latest
    depends_on:
     - usersdb
    networks:
     - back

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.2
    ports:
      - "9200:9200"
    environment:
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
     - back

  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.2
    ports:
      - "5601:5601"
    environment:
      - "xpack.security.enabled=false"
    depends_on:
     - elasticsearch
    networks:
     - back

  logstash:
    image: docker.elastic.co/logstash/logstash:5.2.2
    ports:
      - "25826:25826"
    volumes:
      - ./elk-config/logstash.config:/elk-config/logstash.config
    environment:
     - "xpack.security.enabled=false"
    command: logstash -f /elk-config/logstash.config --config.reload.automatic
    depends_on:
     - elasticsearch
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks:
     - back

  eureka-service:
    image: mateuszsojka/eureka-service:latest
    networks:
     - back
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    depends_on:
     - logstash

  config-server:
    image: mateuszsojka/config-server:latest
    restart: always
    depends_on:
     - eureka-service
    networks:
     - back
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    depends_on:
     - logstash

  auth-service:
    image: mateuszsojka/auth-service:latest
    restart: always
    depends_on:
     - eureka-service
     - config-server
    networks:
     - back
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    depends_on:
     - logstash

  image-service:
    image: mateuszsojka/image-service:latest
    restart: always
    depends_on:
     - eureka-service
     - config-server
    networks:
     - back
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"
    depends_on:
     - logstash

  api-gateway:
    image: mateuszsojka/api-gateway:latest
    restart: always
    depends_on:
     - logstash
     - eureka-service
     - config-server
     - auth-service
     - image-service
    ports:
     - 8080:8080
    networks:
     - back
     - front
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://127.0.0.1:25826"
        tag: "{{.ImageName}}/{{.Name}}/{{.ID}}"

