usersdb:
  container_name: usersdb
  image: mateuszsojka/usersdb:latest
  ports:
   - 5432
videodb:
  container_name: videodb
  image: mateuszsojka/videodb:latest
  ports:
   - 5432
  links:
   - usersdb:usersdb
   
eureka-service:
  image: mateuszsojka/eureka-service:latest
  ports:
   - 8761:8761

config-server:
  image: mateuszsojka/config-server:latest
  restart: always
  ports:
   - 8888:8888
  links:
   - eureka-service:eureka-service

auth-service:
  image: mateuszsojka/auth-service:latest
  restart: always
  ports:
   - 9000:9000
  links:
   - usersdb:usersdb
   - eureka-service:eureka-service
   - config-server:config-server

video-service:
  image: mateuszsojka/video-service:latest
  restart: always
  ports:
  - 9008
  links:
   - videodb:videodb
   - eureka-service:eureka-service
   - config-server:config-server

api-gateway:
  image: mateuszsojka/api-gateway:latest
  restart: always
  ports:
  - 8080:8080
  links:
  - eureka-service:eureka-service
  - config-server:config-server
  - auth-service:auth-service
  - video-service:video-service
