version: "3"

networks:
  front:
  back:

services:
  usersdb:
    container_name: usersdb
    image: mateuszsojka/usersdb:latest
    networks:
     - back
  videodb:
    container_name: videodb
    image: mateuszsojka/videodb:latest
    depends_on:
     - usersdb
    networks:
     - back

  eureka-service:
    image: mateuszsojka/eureka-service:latest
    networks:
     - back
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"

  config-server:
    image: mateuszsojka/config-server:latest
    restart: always
    depends_on:
     - eureka-service
    networks:
     - back
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"

  auth-service:
    image: mateuszsojka/auth-service:latest
    restart: always
    depends_on:
     - eureka-service
     - config-server
    networks:
     - back
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"

  video-service:
    image: mateuszsojka/video-service:latest
    restart: always
    depends_on:
     - eureka-service
     - config-server
    networks:
     - back
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"

  api-gateway:
    image: mateuszsojka/api-gateway:latest
    restart: always
    depends_on:
     - eureka-service
     - config-server
     - auth-service
     - video-service
    ports:
     - 8080:8080
    networks:
     - back
     - front
    environment:
     - "SPRING_PROFILES_ACTIVE=docker"

  streamer-web-app:
    image: mateuszsojka/streamer-web-app:latest
    restart: always
    depends_on:
     - api-gateway
    ports: 
     - 80:80
    networks:
     - front
