version: 1
task_definition:
  task_execution_role: ecsExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 1GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-028e5b4a943fc18fa"
        - "subnet-096c4b61489fc65f7"
      security_groups:
        - "sg-0fb85582e5cbad4d8"
      assign_public_ip: ENABLED