version: 1
task_definition:
  task_execution_role: ecsExecutionRole
  ecs_network_mode: awsvpc
  task_size:
    mem_limit: 1GB
    cpu_limit: 256
run_params:
  network_configuration:
    awsvpc_configuration:
      subnets:
        - "subnet-06a3b4dcdc8f770ec"
        - "subnet-0e14ff08bb028cecc"
      security_groups:
        - "sg-01b13b34ffa02be18"
      assign_public_ip: ENABLED