######################## Httpbeat Configuration Example ########################

############################## Httpbeat ########################################
httpbeat:

hosts:
  # Each - Host endpoints to call. Below are the host endpoint specific configurations
  -
    schedule: "@every 30s"
    url: http://localhost:8080/health
    method: get
    headers:
      Accept: application/json
    output_format: json
    json_dot_mode: replace

  -
    schedule: "@every 30s"
    url: http://localhost:8080/metrics
    method: get
    headers:
      Accept: application/json
    output_format: json
    json_dot_mode: replace

#================================ General =====================================
fields:
app_id: test_app

#----------------------------- Logstash output --------------------------------
output.elasticsearch:
hosts: ["localhost:9200"]
index: "httpbeat-%{+yyyy.MM.dd}"