{{- $image := printf "%s/%s:%s" .Values.dockerRegistry .Values.configServer.imageName .Values.configServerVersion -}}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.configServer.name }}
  labels:
    enviroment: {{ .Values.enviroment }}
    app.kubernetes.io/name: {{ .Values.configServer.name }}
    app.kubernetes.io/version: {{ .Values.configServerVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ .Values.enviroment }}
    app.kubernetes.io/managed-by: helm

spec:
  replicas: {{ .Values.configServer.replicaCount }}
  minReadySeconds: {{ .Values.configServer.minReadySeconds }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: {{ .Values.configServer.maxUnavailable }}
      maxSurge: {{ .Values.configServer.maxSurge }}
  selector:
    matchLabels:
      component: {{ .Values.configServer.name }}
  template:
    metadata:
      labels:
        component: {{ .Values.configServer.name }}
    spec:
      containers:
        - name: {{ .Values.configServer.name }}
          image: {{ $image }}
          imagePullPolicy: {{ .Values.configServer.imagePullPolicy }}
          resources:
            requests:
              memory: {{ .Values.configServer.memoryRequest }}
              cpu: {{ .Values.configServer.cpuRequest }}
            limits:
              memory: {{ .Values.configServer.memoryLimit }}
              cpu: {{ .Values.configServer.cpuLimit }}
          ports:
            - containerPort: {{ .Values.configServer.port }}
          env:
            - name: JAVA_OPTS
              value: {{ .Values.configServer.javaOpts }}
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: env
                  key: SPRING_PROFILES_ACTIVE
