apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-volume-claim
  labels:
    enviroment: {{ .Values.enviroment }}
    app.kubernetes.io/name: {{ .Values.elasticsearch.name }}
    app.kubernetes.io/version: {{ .Values.elasticsearchVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ .Values.enviroment }}
    app.kubernetes.io/managed-by: helm
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.elasticsearch.requestStorage }}
