apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagedb-main-volume-claim
  labels:
    enviroment: {{ .Values.enviroment }}
    app.kubernetes.io/name: {{ .Values.imagedb.name }}
    app.kubernetes.io/version: {{ .Values.imagedbVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ .Values.enviroment }}
    app.kubernetes.io/managed-by: helm
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.imagedb.mainRequestStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagedb-logs-volume-claim
  labels:
    enviroment: {{ .Values.enviroment }}
    app.kubernetes.io/name: {{ .Values.imagedb.name }}
    app.kubernetes.io/version: {{ .Values.imagedbVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ .Values.enviroment }}
    app.kubernetes.io/managed-by: helm
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.imagedb.logsRequestStorage }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: imagedb-libs-volume-claim
  labels:
    enviroment: {{ .Values.enviroment }}
    app.kubernetes.io/name: {{ .Values.imagedb.name }}
    app.kubernetes.io/version: {{ .Values.imagedbVersion }}
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: {{ .Values.enviroment }}
    app.kubernetes.io/managed-by: helm
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: {{ .Values.imagedb.libsRequestStorage }}
